name: one

on:
  workflow_dispatch:
  repository_dispatch:
    types: [first]
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
         
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}

      - name: Install requirements
        run: pip install --upgrade -r requirements.txt 

      - name: update
        run: sudo apt-get -y update
      
      - name: install ffmpeg
        run: sudo apt install -y ffmpeg

      - name: python-lxml
        run: pip3 install lxml

      - name: lxml_html_clean
        run: pip install lxml_html_clean

      - name: erro404
        timeout-minutes: 350
        continue-on-error: true
        run: python3 -m bot
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }} 
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          SUDO_USERS: ${{ secrets.SUDO_USERS }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          LOG_CHANNEL: ${{ secrets.LOG_CHANNEL }}
          
